/**
 * Master Dataset for All Section SFG Report
 * Auto-Linked with Closing All SFG (FAN SFG Category)
 * Date Interval: 2026-08-01 to 2026-08-26
 * Total Records: 135
 */
const RAW_ALL_SECTION_SFG_DATA = [
    {
        "sl":  1,
        "section":  "Body SFG",
        "code":  "SFG1010076",
        "itemName":  "2401 Super Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "production":  1091,
        "delivery":  1091,
        "closing":  0
    },
    {
        "sl":  2,
        "section":  "Body SFG",
        "code":  "SFG1010077",
        "itemName":  "3601 Hero Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  4519,
        "production":  3933,
        "delivery":  5107,
        "closing":  3345
    },
    {
        "sl":  3,
        "section":  "Body SFG",
        "code":  "SFG1010078",
        "itemName":  "4801 Popular Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "production":  1167,
        "delivery":  1100,
        "closing":  67
    },
    {
        "sl":  4,
        "section":  "Body SFG",
        "code":  "SFG1010080",
        "itemName":  "5602 Speed King Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  271,
        "production":  0,
        "delivery":  0,
        "closing":  271
    },
    {
        "sl":  5,
        "section":  "Body SFG",
        "code":  "SFG1010097",
        "itemName":  "5603 Premium Gold Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  89,
        "production":  322,
        "delivery":  0,
        "closing":  411
    },
    {
        "sl":  6,
        "section":  "Body SFG",
        "code":  "SFG1010137",
        "itemName":  "5606 Premium Plus Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "production":  60,
        "delivery":  60,
        "closing":  0
    },
    {
        "sl":  7,
        "section":  "Body SFG",
        "code":  "SFG1010135",
        "itemName":  "5607 Crown Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "production":  335,
        "delivery":  335,
        "closing":  0
    },
    {
        "sl":  8,
        "section":  "Body SFG",
        "code":  "SFG1010111",
        "itemName":  "5601 Premium Ceiling Fan Complete Body-White",
        "unit":  "Pcs",
        "opening":  0,
        "production":  49,
        "delivery":  49,
        "closing":  0
    },
    {
        "sl":  9,
        "section":  "Body SFG",
        "code":  "SFG1010079",
        "itemName":  "5601 Premium Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  4665,
        "production":  24121,
        "delivery":  28786,
        "closing":  0
    },
    {
        "sl":  10,
        "section":  "Body SFG",
        "code":  "SFG1010113",
        "itemName":  "3601 Hero Ceiling Fan Complete Body - Ivory (W.R.)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  11,
        "section":  "Body SFG",
        "code":  "SFG1010118",
        "itemName":  "4801 Popular Ceiling Fan Complete Body - Ivory (W.R.)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  12,
        "section":  "Body SFG",
        "code":  "SFG1010117",
        "itemName":  "5603 Premium Gold Complete Body - Ivory (W.R.)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  13,
        "section":  "Body SFG",
        "code":  "SFG1010138",
        "itemName":  "5606 Premium Plus Ceiling Fan Complete Body - Ivory (W.R)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  14,
        "section":  "Body SFG",
        "code":  "SFG1010112",
        "itemName":  "5601 Premium Ceiling Fan Complete Body - White (W.R.)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  56,
        "delivery":  56,
        "closing":  0
    },
    {
        "sl":  15,
        "section":  "Body SFG",
        "code":  "SFG1010116",
        "itemName":  "5601 Premium Ceiling Fan Complete Body - Ivory (W.R.)",
        "unit":  "Pcs",
        "opening":  6083,
        "production":  0,
        "delivery":  2015,
        "closing":  4068
    },
    {
        "sl":  16,
        "section":  "Body SFG",
        "code":  "SFG1010140",
        "itemName":  "5606 Premium Plus Ceiling Fan Complete Body - Ivory (Gang Regulator)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  17,
        "section":  "Body SFG",
        "code":  "SFG1010120",
        "itemName":  "5601 Premium Ceiling Fan Complete Body -Ivory (Gang Regulator)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  48,
        "delivery":  48,
        "closing":  0
    },
    {
        "sl":  18,
        "section":  "Blade SFG",
        "code":  "SFG1010074",
        "itemName":  "5601 Premium Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  12569,
        "production":  18870,
        "delivery":  30849,
        "closing":  590
    },
    {
        "sl":  19,
        "section":  "Blade SFG",
        "code":  "SFG1010109",
        "itemName":  "5601 Premium Ceiling Fan Blade - White",
        "unit":  "Set",
        "opening":  1,
        "production":  218,
        "delivery":  105,
        "closing":  114
    },
    {
        "sl":  20,
        "section":  "Blade SFG",
        "code":  "SFG1010075",
        "itemName":  "5602 Speed King Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  0,
        "production":  1056,
        "delivery":  0,
        "closing":  1056
    },
    {
        "sl":  21,
        "section":  "Blade SFG",
        "code":  "SFG1010096",
        "itemName":  "5603 Premium Gold Ceiling Fan Blade",
        "unit":  "Set",
        "opening":  5,
        "production":  0,
        "delivery":  0,
        "closing":  5
    },
    {
        "sl":  22,
        "section":  "Blade SFG",
        "code":  "SFG1010139",
        "itemName":  "5606 Premium Plus Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  20,
        "production":  294,
        "delivery":  60,
        "closing":  254
    },
    {
        "sl":  23,
        "section":  "Blade SFG",
        "code":  "SFG1010136",
        "itemName":  "5607 Crown Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  221,
        "production":  263,
        "delivery":  335,
        "closing":  149
    },
    {
        "sl":  24,
        "section":  "Blade SFG",
        "code":  "SFG1010073",
        "itemName":  "4801 Popular Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  2270,
        "production":  213,
        "delivery":  1100,
        "closing":  1383
    },
    {
        "sl":  25,
        "section":  "Blade SFG",
        "code":  "SFG1010072",
        "itemName":  "3601 Hero Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  3342,
        "production":  3260,
        "delivery":  5108,
        "closing":  1494
    },
    {
        "sl":  26,
        "section":  "Blade SFG",
        "code":  "SFG1010071",
        "itemName":  "2401 Super Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  493,
        "production":  3840,
        "delivery":  1091,
        "closing":  3242
    },
    {
        "sl":  27,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010019",
        "itemName":  "Armature 5.5 Circle 16mm",
        "unit":  "Pcs",
        "opening":  8990,
        "production":  0,
        "delivery":  1850,
        "closing":  7140
    },
    {
        "sl":  28,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010020",
        "itemName":  "Armature 6 Circle 16 mm",
        "unit":  "Pcs",
        "opening":  11303,
        "production":  0,
        "delivery":  178,
        "closing":  11125
    },
    {
        "sl":  29,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010021",
        "itemName":  "Armature 6 Circle 15mm Black Sheet",
        "unit":  "Pcs",
        "opening":  506,
        "production":  0,
        "delivery":  0,
        "closing":  506
    },
    {
        "sl":  30,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010022",
        "itemName":  "Armature 7 Circle 15mm",
        "unit":  "Pcs",
        "opening":  18399,
        "production":  29863,
        "delivery":  15000,
        "closing":  33262
    },
    {
        "sl":  31,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010121",
        "itemName":  "Armature 7 Circle 16mm",
        "unit":  "Pcs",
        "opening":  1424,
        "production":  0,
        "delivery":  160,
        "closing":  1264
    },
    {
        "sl":  32,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010031",
        "itemName":  "Rotor 5.5 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  0,
        "production":  6000,
        "delivery":  6000,
        "closing":  0
    },
    {
        "sl":  33,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010032",
        "itemName":  "Rotor 6 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  34,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010033",
        "itemName":  "Rotor 6 Circle 14.5mm Black Sheet",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  35,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010034",
        "itemName":  "Rotor 7 Circle 14.5mm",
        "unit":  "Pcs",
        "opening":  24140,
        "production":  31012,
        "delivery":  40105,
        "closing":  15047
    },
    {
        "sl":  36,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010124",
        "itemName":  "Rotor 7 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  37,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010046",
        "itemName":  "MS Blade 2401 (Sheet)",
        "unit":  "Set",
        "opening":  14,
        "production":  0,
        "delivery":  0,
        "closing":  14
    },
    {
        "sl":  38,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010047",
        "itemName":  "MS Blade 5602 (Sheet)",
        "unit":  "Set",
        "opening":  210,
        "production":  0,
        "delivery":  0,
        "closing":  210
    },
    {
        "sl":  39,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010043",
        "itemName":  "Aluminum Blade 3601 (Sheet)",
        "unit":  "Set",
        "opening":  2992,
        "production":  4216,
        "delivery":  1714,
        "closing":  5494
    },
    {
        "sl":  40,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010044",
        "itemName":  "Aluminum Blade 4801 (Sheet)",
        "unit":  "Set",
        "opening":  16,
        "production":  2200,
        "delivery":  0,
        "closing":  2216
    },
    {
        "sl":  41,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010093",
        "itemName":  "Aluminum Blade 5603",
        "unit":  "Set",
        "opening":  4019,
        "production":  0,
        "delivery":  3530,
        "closing":  489
    },
    {
        "sl":  42,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010127",
        "itemName":  "Aluminum Blade 5607",
        "unit":  "Set",
        "opening":  41,
        "production":  0,
        "delivery":  0,
        "closing":  41
    },
    {
        "sl":  43,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010045",
        "itemName":  "Aluminum Blade 5601 (Sheet)",
        "unit":  "Set",
        "opening":  12098,
        "production":  15408,
        "delivery":  21442,
        "closing":  6064
    },
    {
        "sl":  44,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010048",
        "itemName":  "Blade MS Shank (3601)",
        "unit":  "Set",
        "opening":  376,
        "production":  5932,
        "delivery":  1714,
        "closing":  4594
    },
    {
        "sl":  45,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010050",
        "itemName":  "Blade MS Shank (5602)",
        "unit":  "Set",
        "opening":  3390,
        "production":  0,
        "delivery":  0,
        "closing":  3390
    },
    {
        "sl":  46,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010098",
        "itemName":  "Blade MS Shank (5603)",
        "unit":  "Set",
        "opening":  80,
        "production":  4450,
        "delivery":  3530,
        "closing":  1000
    },
    {
        "sl":  47,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010128",
        "itemName":  "Blade MS Shank (5607)",
        "unit":  "Set",
        "opening":  35,
        "production":  0,
        "delivery":  0,
        "closing":  35
    },
    {
        "sl":  48,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010049",
        "itemName":  "Blade MS Shank (5601,4801)",
        "unit":  "Set",
        "opening":  21170,
        "production":  3386,
        "delivery":  21442,
        "closing":  3114
    },
    {
        "sl":  49,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010061",
        "itemName":  "Down Pipe 10 Inch -(5602,3601,2401)",
        "unit":  "Pcs",
        "opening":  4400,
        "production":  0,
        "delivery":  4400,
        "closing":  0
    },
    {
        "sl":  50,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010060",
        "itemName":  "Down Pipe 10 Inch- 4801, 5601, 5603",
        "unit":  "Pcs",
        "opening":  3755,
        "production":  25667,
        "delivery":  22956,
        "closing":  6466
    },
    {
        "sl":  51,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010066",
        "itemName":  "Down Pipe Clamp - 4801, 5601, 5603",
        "unit":  "Set",
        "opening":  28491,
        "production":  8330,
        "delivery":  10614,
        "closing":  26207
    },
    {
        "sl":  52,
        "section":  "Power Press \u0026 Stamping",
        "code":  "SFG1010102",
        "itemName":  "Down Pipe 1 Inch - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "production":  22000,
        "delivery":  22000,
        "closing":  0
    },
    {
        "sl":  53,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010101",
        "itemName":  "FAN Aluminium Bar",
        "unit":  "Kg",
        "opening":  114.256,
        "production":  41287.3,
        "delivery":  41389.4,
        "closing":  512.156
    },
    {
        "sl":  54,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010001",
        "itemName":  "Top Cover - 2401 (184mm)",
        "unit":  "Pcs",
        "opening":  2462,
        "production":  0,
        "delivery":  950,
        "closing":  1512
    },
    {
        "sl":  55,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010083",
        "itemName":  "Top Cover - 3601 (184mm)",
        "unit":  "Pcs",
        "opening":  8848,
        "production":  4000,
        "delivery":  7000,
        "closing":  5848
    },
    {
        "sl":  56,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010002",
        "itemName":  "Top Cover-4801 (220mm)",
        "unit":  "Pcs",
        "opening":  2697,
        "production":  3200,
        "delivery":  2500,
        "closing":  3397
    },
    {
        "sl":  57,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010004",
        "itemName":  "Top Cover-5602 (217mm)",
        "unit":  "Pcs",
        "opening":  1106,
        "production":  7800,
        "delivery":  0,
        "closing":  8906
    },
    {
        "sl":  58,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010084",
        "itemName":  "Top Cover-5603 (232mm)",
        "unit":  "Pcs",
        "opening":  3000,
        "production":  0,
        "delivery":  3000,
        "closing":  0
    },
    {
        "sl":  59,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010131",
        "itemName":  "Top Cover - 5607",
        "unit":  "Pcs",
        "opening":  992,
        "production":  0,
        "delivery":  0,
        "closing":  992
    },
    {
        "sl":  60,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010003",
        "itemName":  "Top Cover-5601 (232mm)",
        "unit":  "Pcs",
        "opening":  30053,
        "production":  6000,
        "delivery":  11115,
        "closing":  24938
    },
    {
        "sl":  61,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010010",
        "itemName":  "Bottom Cover - 3601, 2401 (184mm)",
        "unit":  "Pcs",
        "opening":  0,
        "production":  4000,
        "delivery":  4000,
        "closing":  0
    },
    {
        "sl":  62,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010011",
        "itemName":  "Bottom Cover-4801 (220mm)",
        "unit":  "Pcs",
        "opening":  3630,
        "production":  2700,
        "delivery":  2000,
        "closing":  4330
    },
    {
        "sl":  63,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010013",
        "itemName":  "Bottom Cover-5602 (217mm)",
        "unit":  "Pcs",
        "opening":  96,
        "production":  7800,
        "delivery":  0,
        "closing":  7896
    },
    {
        "sl":  64,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010091",
        "itemName":  "Bottom Cover-5603 (232mm)",
        "unit":  "Pcs",
        "opening":  3551,
        "production":  0,
        "delivery":  900,
        "closing":  2651
    },
    {
        "sl":  65,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010132",
        "itemName":  "Bottom Cover - 5607",
        "unit":  "Pcs",
        "opening":  2341,
        "production":  0,
        "delivery":  0,
        "closing":  2341
    },
    {
        "sl":  66,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010012",
        "itemName":  "Bottom Cover-5601 (232mm)",
        "unit":  "Pcs",
        "opening":  29894,
        "production":  6500,
        "delivery":  12980,
        "closing":  23414
    },
    {
        "sl":  67,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010035",
        "itemName":  "Rotor with Ingot 5.5 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  16896,
        "production":  6000,
        "delivery":  9630,
        "closing":  13266
    },
    {
        "sl":  68,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010036",
        "itemName":  "Rotor with Ingot 6 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  12077,
        "production":  0,
        "delivery":  100,
        "closing":  11977
    },
    {
        "sl":  69,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010037",
        "itemName":  "Rotor with Ingot 6 Circle 14.5mm Black Sheet",
        "unit":  "Pcs",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  70,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010038",
        "itemName":  "Rotor with Ingot 7 Circle 14.5mm",
        "unit":  "Pcs",
        "opening":  20586,
        "production":  40105,
        "delivery":  20405,
        "closing":  40286
    },
    {
        "sl":  71,
        "section":  "Dhalai \u0026 Die Casting",
        "code":  "SFG1010125",
        "itemName":  "Rotor with Ingot 7 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  1909,
        "production":  0,
        "delivery":  351,
        "closing":  1558
    },
    {
        "sl":  72,
        "section":  "Fan Lathe",
        "code":  "SFG1010039",
        "itemName":  "Complete Rotor 5.5 Circle 15.5mm",
        "unit":  "PCS",
        "opening":  208,
        "production":  9630,
        "delivery":  5024,
        "closing":  4814
    },
    {
        "sl":  73,
        "section":  "Fan Lathe",
        "code":  "SFG1010040",
        "itemName":  "Complete Rotor 6 Circle 15.5mm",
        "unit":  "PCS",
        "opening":  1368,
        "production":  100,
        "delivery":  1167,
        "closing":  301
    },
    {
        "sl":  74,
        "section":  "Fan Lathe",
        "code":  "SFG1010041",
        "itemName":  "Complete Rotor 6 Circle 14.5mm Black Sheet",
        "unit":  "PCS",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  75,
        "section":  "Fan Lathe",
        "code":  "SFG1010042",
        "itemName":  "Complete Rotor 7 Circle 14.5mm",
        "unit":  "PCS",
        "opening":  7126,
        "production":  20405,
        "delivery":  24596,
        "closing":  2935
    },
    {
        "sl":  76,
        "section":  "Fan Lathe",
        "code":  "SFG1010126",
        "itemName":  "Complete Rotor 7 Circle 15.5mm",
        "unit":  "PCS",
        "opening":  241,
        "production":  351,
        "delivery":  395,
        "closing":  197
    },
    {
        "sl":  77,
        "section":  "Fan Lathe",
        "code":  "SFG1010099",
        "itemName":  "Bottom Cover - 2401 (184mm)",
        "unit":  "PCS",
        "opening":  4990,
        "production":  0,
        "delivery":  2976,
        "closing":  2014
    },
    {
        "sl":  78,
        "section":  "Fan Lathe",
        "code":  "SFG1010100",
        "itemName":  "Bottom Cover - 3601 (184mm)",
        "unit":  "PCS",
        "opening":  6593,
        "production":  4000,
        "delivery":  6000,
        "closing":  4593
    },
    {
        "sl":  79,
        "section":  "Fan Armature",
        "code":  "SFG1010023",
        "itemName":  "Winding Armature 5.5 Circle 16mm",
        "unit":  "PCS",
        "opening":  3174,
        "production":  1850,
        "delivery":  5024,
        "closing":  0
    },
    {
        "sl":  80,
        "section":  "Fan Armature",
        "code":  "SFG1010024",
        "itemName":  "Winding Armature 6 Circle 16mm",
        "unit":  "PCS",
        "opening":  2123,
        "production":  178,
        "delivery":  1241,
        "closing":  1060
    },
    {
        "sl":  81,
        "section":  "Fan Armature",
        "code":  "SFG1010025",
        "itemName":  "Winding Armature 6 Circle 15mm Black Sheet",
        "unit":  "PCS",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  82,
        "section":  "Fan Armature",
        "code":  "SFG1010026",
        "itemName":  "Winding Armature 7 Circle 15mm",
        "unit":  "PCS",
        "opening":  11331,
        "production":  15000,
        "delivery":  18824,
        "closing":  7507
    },
    {
        "sl":  83,
        "section":  "Fan Armature",
        "code":  "SFG1010122",
        "itemName":  "Winding Armature 7 Circle 16mm",
        "unit":  "PCS",
        "opening":  788,
        "production":  160,
        "delivery":  396,
        "closing":  552
    },
    {
        "sl":  84,
        "section":  "Fan Armature",
        "code":  "SFG1010027",
        "itemName":  "Complete Armature 5.5 Circle 16mm",
        "unit":  "PCS",
        "opening":  60,
        "production":  5024,
        "delivery":  5024,
        "closing":  60
    },
    {
        "sl":  85,
        "section":  "Fan Armature",
        "code":  "SFG1010028",
        "itemName":  "Complete Armature 6 Circle 16mm",
        "unit":  "PCS",
        "opening":  0,
        "production":  1241,
        "delivery":  1167,
        "closing":  74
    },
    {
        "sl":  86,
        "section":  "Fan Armature",
        "code":  "SFG1010029",
        "itemName":  "Complete Armature 6 Circle 15mm Black Sheet",
        "unit":  "PCS",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  87,
        "section":  "Fan Armature",
        "code":  "SFG1010030",
        "itemName":  "Complete Armature 7 Circle 15mm",
        "unit":  "PCS",
        "opening":  6095,
        "production":  18824,
        "delivery":  24596,
        "closing":  323
    },
    {
        "sl":  88,
        "section":  "Fan Armature",
        "code":  "SFG1010141",
        "itemName":  "Complete Armature 7 Circle 16mm -5606",
        "unit":  "PCS",
        "opening":  0,
        "production":  60,
        "delivery":  60,
        "closing":  0
    },
    {
        "sl":  89,
        "section":  "Fan Armature",
        "code":  "SFG1010123",
        "itemName":  "Complete Armature 7 Circle 16mm -5607",
        "unit":  "PCS",
        "opening":  0,
        "production":  336,
        "delivery":  335,
        "closing":  1
    },
    {
        "sl":  90,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010005",
        "itemName":  "Painting Top Cover-2401 (184mm)- Ivory",
        "unit":  "Pcs",
        "opening":  2488,
        "production":  950,
        "delivery":  1091,
        "closing":  2347
    },
    {
        "sl":  91,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010006",
        "itemName":  "Painting Top Cover-3601 (184mm) - Ivory",
        "unit":  "Pcs",
        "opening":  761,
        "production":  7000,
        "delivery":  3933,
        "closing":  3828
    },
    {
        "sl":  92,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010007",
        "itemName":  "Painting Top Cover-4801 (220mm) - Ivory",
        "unit":  "Pcs",
        "opening":  1398,
        "production":  2500,
        "delivery":  1167,
        "closing":  2731
    },
    {
        "sl":  93,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010009",
        "itemName":  "Painting Top Cover-5602 (217mm) - Ivory",
        "unit":  "Pcs",
        "opening":  4005,
        "production":  0,
        "delivery":  0,
        "closing":  4005
    },
    {
        "sl":  94,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010090",
        "itemName":  "Painting Top Cover-5603 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  1205,
        "production":  3000,
        "delivery":  322,
        "closing":  3883
    },
    {
        "sl":  95,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010133",
        "itemName":  "Painting Top Cover 5607 - Ivory",
        "unit":  "Pcs",
        "opening":  870,
        "production":  0,
        "delivery":  335,
        "closing":  535
    },
    {
        "sl":  96,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010105",
        "itemName":  "Painting Top Cover-5601 (232mm) - White",
        "unit":  "Pcs",
        "opening":  15,
        "production":  215,
        "delivery":  105,
        "closing":  125
    },
    {
        "sl":  97,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010008",
        "itemName":  "Painting Top Cover-5601 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  16897,
        "production":  10900,
        "delivery":  24229,
        "closing":  3568
    },
    {
        "sl":  98,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010014",
        "itemName":  "Painting Bottom Cover-2401 (184mm) - Ivory",
        "unit":  "Pcs",
        "opening":  924,
        "production":  2976,
        "delivery":  1091,
        "closing":  2809
    },
    {
        "sl":  99,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010015",
        "itemName":  "Painting Bottom Cover-3601 (184mm) - Ivory",
        "unit":  "Pcs",
        "opening":  2442,
        "production":  6000,
        "delivery":  3933,
        "closing":  4509
    },
    {
        "sl":  100,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010016",
        "itemName":  "Painting Bottom Cover-4801 (220mm) - Ivory",
        "unit":  "Pcs",
        "opening":  1842,
        "production":  2000,
        "delivery":  1167,
        "closing":  2675
    },
    {
        "sl":  101,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010018",
        "itemName":  "Painting Bottom Cover-5602 (217mm) - Ivory",
        "unit":  "Pcs",
        "opening":  4173,
        "production":  0,
        "delivery":  0,
        "closing":  4173
    },
    {
        "sl":  102,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010092",
        "itemName":  "Painting Bottom Cover-5603 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  719,
        "production":  900,
        "delivery":  322,
        "closing":  1297
    },
    {
        "sl":  103,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010134",
        "itemName":  "Painting Bottom Cover 5607 - Ivory",
        "unit":  "Pcs",
        "opening":  787,
        "production":  0,
        "delivery":  335,
        "closing":  452
    },
    {
        "sl":  104,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010106",
        "itemName":  "Painting Bottom Cover-5601 (232mm) - White",
        "unit":  "Pcs",
        "opening":  150,
        "production":  80,
        "delivery":  105,
        "closing":  125
    },
    {
        "sl":  105,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010017",
        "itemName":  "Painting Bottom Cover-5601 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  16267,
        "production":  12900,
        "delivery":  24229,
        "closing":  4938
    },
    {
        "sl":  106,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010051",
        "itemName":  "Blade With Shank 3601",
        "unit":  "Set",
        "opening":  49,
        "production":  1714,
        "delivery":  1600,
        "closing":  163
    },
    {
        "sl":  107,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010052",
        "itemName":  "Blade With Shank 4801",
        "unit":  "Set",
        "opening":  4,
        "production":  0,
        "delivery":  0,
        "closing":  4
    },
    {
        "sl":  108,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010054",
        "itemName":  "Blade With Shank 5602",
        "unit":  "Set",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  109,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010089",
        "itemName":  "Blade With Shank 5603",
        "unit":  "Set",
        "opening":  0,
        "production":  3530,
        "delivery":  3500,
        "closing":  30
    },
    {
        "sl":  110,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010129",
        "itemName":  "Blade With Shank 5607",
        "unit":  "Set",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  111,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010053",
        "itemName":  "Blade With Shank 5601",
        "unit":  "Set",
        "opening":  500,
        "production":  21442,
        "delivery":  19830,
        "closing":  2112
    },
    {
        "sl":  112,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010055",
        "itemName":  "Painting Blade 2401-Ivory",
        "unit":  "Set",
        "opening":  5538,
        "production":  0,
        "delivery":  3840,
        "closing":  1698
    },
    {
        "sl":  113,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010056",
        "itemName":  "Painting Blade 3601-Ivory",
        "unit":  "Set",
        "opening":  3265,
        "production":  1600,
        "delivery":  3260,
        "closing":  1605
    },
    {
        "sl":  114,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010057",
        "itemName":  "Painting Blade 4801-Ivory",
        "unit":  "Set",
        "opening":  590,
        "production":  0,
        "delivery":  213,
        "closing":  377
    },
    {
        "sl":  115,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010059",
        "itemName":  "Painting Blade 5602-Ivory",
        "unit":  "Set",
        "opening":  1121,
        "production":  0,
        "delivery":  1056,
        "closing":  65
    },
    {
        "sl":  116,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010095",
        "itemName":  "Painting Blade 5603-Ivory",
        "unit":  "Set",
        "opening":  419,
        "production":  3500,
        "delivery":  0,
        "closing":  3919
    },
    {
        "sl":  117,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010130",
        "itemName":  "Painting Blade 5607 - Ivory",
        "unit":  "Set",
        "opening":  1347,
        "production":  0,
        "delivery":  263,
        "closing":  1084
    },
    {
        "sl":  118,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010107",
        "itemName":  "Painting Blade 5601-White",
        "unit":  "Set",
        "opening":  0,
        "production":  218,
        "delivery":  218,
        "closing":  0
    },
    {
        "sl":  119,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010058",
        "itemName":  "Painting Blade 5601-Ivory",
        "unit":  "Set",
        "opening":  3373,
        "production":  19612,
        "delivery":  19164,
        "closing":  3821
    },
    {
        "sl":  120,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010062",
        "itemName":  "Painted Down Pipe 10 Inch- 4801, 5601, 5603 - Ivory",
        "unit":  "Pcs",
        "opening":  13075,
        "production":  22621,
        "delivery":  19953,
        "closing":  15743
    },
    {
        "sl":  121,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010114",
        "itemName":  "Painted Down Pipe 10 Inch- 4801, 5601, 5603 - White",
        "unit":  "Pcs",
        "opening":  0,
        "production":  335,
        "delivery":  335,
        "closing":  0
    },
    {
        "sl":  122,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010063",
        "itemName":  "Painted Down Pipe 10 Inch-5602,3601,2401 - Ivory",
        "unit":  "Pcs",
        "opening":  6146,
        "production":  4400,
        "delivery":  9884,
        "closing":  662
    },
    {
        "sl":  123,
        "section":  "Auto Powder Coating",
        "code":  "SFG1010103",
        "itemName":  "Painting Down pipe 1 Inch",
        "unit":  "Inch",
        "opening":  0,
        "production":  22000,
        "delivery":  22000,
        "closing":  0
    },
    {
        "sl":  124,
        "section":  "Assemble",
        "code":  "SFG1010064",
        "itemName":  "Complete Down Pipe 10 Inch- 4801, 5601, 5603 - Ivory",
        "unit":  "PCS",
        "opening":  14245,
        "production":  19953,
        "delivery":  25718,
        "closing":  8060
    },
    {
        "sl":  125,
        "section":  "Assemble",
        "code":  "SFG1010115",
        "itemName":  "Complete Down Pipe 10 Inch- 5601- White",
        "unit":  "PCS",
        "opening":  0,
        "production":  335,
        "delivery":  105,
        "closing":  230
    },
    {
        "sl":  126,
        "section":  "Assemble",
        "code":  "SFG1010065",
        "itemName":  "Complete Down Pipe 10 Inch -(5602,3601,2401)- Ivory",
        "unit":  "PCS",
        "opening":  2498,
        "production":  9884,
        "delivery":  5024,
        "closing":  7173
    },
    {
        "sl":  127,
        "section":  "Assemble",
        "code":  "CFDP01/FDP001IV",
        "itemName":  "Celling Fan Down Pipe 1 Inch -Ivory",
        "unit":  "PCS",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  128,
        "section":  "Assemble",
        "code":  "SFG1010082",
        "itemName":  "Completed Clamp with Accessories - 4801, 5601, 5603",
        "unit":  "Set",
        "opening":  17830,
        "production":  10278,
        "delivery":  25823,
        "closing":  1865
    },
    {
        "sl":  129,
        "section":  "Assemble",
        "code":  "SFG1010142",
        "itemName":  "Completed Clamp with Accessories - 5607",
        "unit":  "Set",
        "opening":  0,
        "production":  336,
        "delivery":  335,
        "closing":  1
    },
    {
        "sl":  130,
        "section":  "Assemble",
        "code":  "SFG1010068",
        "itemName":  "Complete Canopy Small-3601,2401",
        "unit":  "PCS",
        "opening":  0,
        "production":  0,
        "delivery":  0,
        "closing":  0
    },
    {
        "sl":  131,
        "section":  "Assemble",
        "code":  "SFG1010069",
        "itemName":  "Complete Canopy Small-5602",
        "unit":  "PCS",
        "opening":  1058,
        "production":  3342,
        "delivery":  0,
        "closing":  4400
    },
    {
        "sl":  132,
        "section":  "Assemble",
        "code":  "SFG1010110",
        "itemName":  "Complete Canopy Big-5601-White",
        "unit":  "PCS",
        "opening":  600,
        "production":  50,
        "delivery":  105,
        "closing":  545
    },
    {
        "sl":  133,
        "section":  "Assemble",
        "code":  "SFG1010070",
        "itemName":  "Complete Canopy Big - 4801, 5601, 5603",
        "unit":  "PCS",
        "opening":  9105,
        "production":  28822,
        "delivery":  30742,
        "closing":  6854
    },
    {
        "sl":  134,
        "section":  "Assemble",
        "code":  "SFG1010081",
        "itemName":  "MEP Fan Regulator - 3601, 4801, 5601, 5603",
        "unit":  "PCS",
        "opening":  11644,
        "production":  39857,
        "delivery":  29652,
        "closing":  21318
    },
    {
        "sl":  135,
        "section":  "Assemble",
        "code":  "SFG1010119",
        "itemName":  "Fan Promotional Gang Regulator White (P512)",
        "unit":  "PCS",
        "opening":  627,
        "production":  0,
        "delivery":  383,
        "closing":  244
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { RAW_ALL_SECTION_SFG_DATA };
}
