/**
 * Closing All SFG - Stock Movement Report (FAN SFG Category Only)
 * Date Interval: 2026-08-01 to 2026-08-20
 * Filter: Category === 'FAN SFG'
 * Total Records: 117
 */
const RAW_CLOSING_ALL_SFG_DATA = [
    {
        "sl":  1,
        "origSl":  "324",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100071",
        "code":  "SFG1010071",
        "itemName":  "2401 Super Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  493,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  3840,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  4333,
        "consumption":  1091,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1091,
        "closing":  3242,
        "binClosing":  3242,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  2,
        "origSl":  "325",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100076",
        "code":  "SFG1010076",
        "itemName":  "2401 Super Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  1091,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1091,
        "consumption":  1091,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1091,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  3,
        "origSl":  "326",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100072",
        "code":  "SFG1010072",
        "itemName":  "3601 Hero Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  3342,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  1860,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  5202,
        "consumption":  5107,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  5107,
        "closing":  95,
        "binClosing":  95,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  4,
        "origSl":  "327",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100077",
        "code":  "SFG1010077",
        "itemName":  "3601 Hero Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  4519,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  600,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  5119,
        "consumption":  5107,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  5107,
        "closing":  12,
        "binClosing":  12,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  5,
        "origSl":  "328",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100073",
        "code":  "SFG1010073",
        "itemName":  "4801 Popular Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  2270,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  213,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  2483,
        "consumption":  1100,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1100,
        "closing":  1383,
        "binClosing":  1383,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  6,
        "origSl":  "329",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100078",
        "code":  "SFG1010078",
        "itemName":  "4801 Popular Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  1167,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1167,
        "consumption":  1100,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1100,
        "closing":  67,
        "binClosing":  67,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  7,
        "origSl":  "330",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100074",
        "code":  "SFG1010074",
        "itemName":  "5601 Premium Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  12569,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  15455,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  28024,
        "consumption":  28024,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  28024,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  8,
        "origSl":  "331",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100111",
        "code":  "SFG1010109",
        "itemName":  "5601 Premium Ceiling Fan Blade - White",
        "unit":  "Set",
        "opening":  1,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  218,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  219,
        "consumption":  105,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  105,
        "closing":  114,
        "binClosing":  114,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  9,
        "origSl":  "332",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100079",
        "code":  "SFG1010079",
        "itemName":  "5601 Premium Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  4665,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  21647,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  26312,
        "consumption":  25961,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  25961,
        "closing":  351,
        "binClosing":  351,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  10,
        "origSl":  "333",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100113",
        "code":  "SFG1010116",
        "itemName":  "5601 Premium Ceiling Fan Complete Body - Ivory (W.R.)",
        "unit":  "Pcs",
        "opening":  6083,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  6083,
        "consumption":  2015,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2015,
        "closing":  4068,
        "binClosing":  4068,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  11,
        "origSl":  "334",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100107",
        "code":  "SFG1010112",
        "itemName":  "5601 Premium Ceiling Fan Complete Body - White (W.R.)",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  56,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  56,
        "consumption":  56,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  56,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  12,
        "origSl":  "335",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100117",
        "code":  "SFG1010120",
        "itemName":  "5601 Premium Ceiling Fan Complete Body -Ivory (Gang Regulator)",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  48,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  48,
        "consumption":  48,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  48,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  13,
        "origSl":  "336",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100106",
        "code":  "SFG1010111",
        "itemName":  "5601 Premium Ceiling Fan Complete Body-White",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  49,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  49,
        "consumption":  49,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  49,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  14,
        "origSl":  "337",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100080",
        "code":  "SFG1010080",
        "itemName":  "5602 Speed King Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  271,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  271,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  271,
        "binClosing":  271,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  15,
        "origSl":  "338",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100091",
        "code":  "SFG1010096",
        "itemName":  "5603 Premium Gold Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  5,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  5,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  5,
        "binClosing":  5,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  16,
        "origSl":  "339",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100092",
        "code":  "SFG1010097",
        "itemName":  "5603 Premium Gold Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  89,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  322,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  411,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  411,
        "binClosing":  411,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  17,
        "origSl":  "340",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100136",
        "code":  "SFG1010139",
        "itemName":  "5606 Premium Plus Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  20,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  294,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  314,
        "consumption":  60,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  60,
        "closing":  254,
        "binClosing":  254,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  18,
        "origSl":  "341",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100134",
        "code":  "SFG1010137",
        "itemName":  "5606 Premium Plus Ceiling Fan Complete Body - Ivory",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  60,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  60,
        "consumption":  60,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  60,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  19,
        "origSl":  "342",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100133",
        "code":  "SFG1010136",
        "itemName":  "5607 Crown Ceiling Fan Blade - Ivory",
        "unit":  "Set",
        "opening":  221,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  263,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  484,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  484,
        "binClosing":  484,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  20,
        "origSl":  "343",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100140",
        "code":  "SFG1010143",
        "itemName":  "Aluminium Bar (SFG)",
        "unit":  "KG",
        "opening":  503.874,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  17680,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  18183.874,
        "consumption":  18002.1,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  18002.1,
        "closing":  181.774,
        "binClosing":  181.774,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  21,
        "origSl":  "344",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100043",
        "code":  "SFG1010043",
        "itemName":  "Aluminum Blade 3601 (Sheet)",
        "unit":  "Set",
        "opening":  2992,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  4666,
        "prodReceive":  4216,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  11874,
        "consumption":  1714,
        "wipIssue":  4666,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  6380,
        "closing":  5494,
        "binClosing":  5494,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  22,
        "origSl":  "345",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100044",
        "code":  "SFG1010044",
        "itemName":  "Aluminum Blade 4801 (Sheet)",
        "unit":  "Set",
        "opening":  16,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  2200,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  2216,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  2216,
        "binClosing":  2216,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  23,
        "origSl":  "346",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100045",
        "code":  "SFG1010045",
        "itemName":  "Aluminum Blade 5601 (Sheet)",
        "unit":  "Set",
        "opening":  12098,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  7825,
        "prodReceive":  8408,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  28331,
        "consumption":  14442,
        "wipIssue":  7825,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  22267,
        "closing":  6064,
        "binClosing":  6064,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  24,
        "origSl":  "347",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100088",
        "code":  "SFG1010093",
        "itemName":  "Aluminum Blade 5603",
        "unit":  "Set",
        "opening":  4019,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  3916,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  7935,
        "consumption":  3530,
        "wipIssue":  3916,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  7446,
        "closing":  489,
        "binClosing":  489,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  25,
        "origSl":  "348",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100124",
        "code":  "SFG1010127",
        "itemName":  "Aluminum Blade 5607",
        "unit":  "Set",
        "opening":  41,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  41,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  41,
        "binClosing":  41,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  26,
        "origSl":  "349",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100019",
        "code":  "SFG1010019",
        "itemName":  "Armature 5.5 Circle 16mm",
        "unit":  "Pcs",
        "opening":  8990,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1850,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  10840,
        "consumption":  1850,
        "wipIssue":  1850,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  3700,
        "closing":  7140,
        "binClosing":  7140,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  27,
        "origSl":  "350",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100021",
        "code":  "SFG1010021",
        "itemName":  "Armature 6 Circle 15mm Black Sheet",
        "unit":  "Pcs",
        "opening":  506,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  506,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  506,
        "binClosing":  506,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  28,
        "origSl":  "351",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100020",
        "code":  "SFG1010020",
        "itemName":  "Armature 6 Circle 16 mm",
        "unit":  "Pcs",
        "opening":  11303,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  11303,
        "consumption":  178,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  178,
        "closing":  11125,
        "binClosing":  11125,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  29,
        "origSl":  "352",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100022",
        "code":  "SFG1010022",
        "itemName":  "Armature 7 Circle 15mm",
        "unit":  "Pcs",
        "opening":  18399,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  21589,
        "prodReceive":  22702,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  62690,
        "consumption":  11500,
        "wipIssue":  21589,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  33089,
        "closing":  29601,
        "binClosing":  29601,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  30,
        "origSl":  "353",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100118",
        "code":  "SFG1010121",
        "itemName":  "Armature 7 Circle 16mm",
        "unit":  "Pcs",
        "opening":  1424,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  240,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1664,
        "consumption":  160,
        "wipIssue":  240,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  400,
        "closing":  1264,
        "binClosing":  1264,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  31,
        "origSl":  "354",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100048",
        "code":  "SFG1010048",
        "itemName":  "Blade MS Shank (3601)",
        "unit":  "Set",
        "opening":  376,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  3606,
        "prodReceive":  3899,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  7881,
        "consumption":  1714,
        "wipIssue":  3606,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  5320,
        "closing":  2561,
        "binClosing":  2561,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  32,
        "origSl":  "355",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100049",
        "code":  "SFG1010049",
        "itemName":  "Blade MS Shank (5601,4801)",
        "unit":  "Set",
        "opening":  21170,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  11934,
        "prodReceive":  3386,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  36490,
        "consumption":  14442,
        "wipIssue":  11934,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  26376,
        "closing":  10114,
        "binClosing":  10114,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  33,
        "origSl":  "356",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100050",
        "code":  "SFG1010050",
        "itemName":  "Blade MS Shank (5602)",
        "unit":  "Set",
        "opening":  3390,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  3390,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  3390,
        "binClosing":  3390,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  34,
        "origSl":  "357",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100093",
        "code":  "SFG1010098",
        "itemName":  "Blade MS Shank (5603)",
        "unit":  "Set",
        "opening":  80,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  3450,
        "prodReceive":  4450,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  7980,
        "consumption":  3530,
        "wipIssue":  3450,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  6980,
        "closing":  1000,
        "binClosing":  1000,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  35,
        "origSl":  "358",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100125",
        "code":  "SFG1010128",
        "itemName":  "Blade MS Shank (5607)",
        "unit":  "Set",
        "opening":  35,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  35,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  35,
        "binClosing":  35,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  36,
        "origSl":  "359",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100051",
        "code":  "SFG1010051",
        "itemName":  "Blade With Shank 3601",
        "unit":  "Set",
        "opening":  49,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  1714,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1763,
        "consumption":  1600,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1600,
        "closing":  163,
        "binClosing":  163,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  37,
        "origSl":  "360",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100052",
        "code":  "SFG1010052",
        "itemName":  "Blade With Shank 4801",
        "unit":  "Set",
        "opening":  4,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  4,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  4,
        "binClosing":  4,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  38,
        "origSl":  "361",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100053",
        "code":  "SFG1010053",
        "itemName":  "Blade With Shank 5601",
        "unit":  "Set",
        "opening":  500,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  14442,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  14942,
        "consumption":  13550,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  13550,
        "closing":  1392,
        "binClosing":  1392,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  39,
        "origSl":  "362",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100089",
        "code":  "SFG1010089",
        "itemName":  "Blade With Shank 5603",
        "unit":  "Set",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  3530,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  3530,
        "consumption":  2800,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2800,
        "closing":  730,
        "binClosing":  730,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  40,
        "origSl":  "363",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100010",
        "code":  "SFG1010010",
        "itemName":  "Bottom Cover - 3601, 2401 (184mm)",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  4000,
        "prodReceive":  4000,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  8000,
        "consumption":  4000,
        "wipIssue":  4000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  8000,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  41,
        "origSl":  "364",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100094",
        "code":  "SFG1010099",
        "itemName":  "Bottom Cover - 2401 (184mm)",
        "unit":  "Pcs",
        "opening":  4990,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  4990,
        "consumption":  2976,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2976,
        "closing":  2014,
        "binClosing":  2014,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  42,
        "origSl":  "365",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100095",
        "code":  "SFG1010100",
        "itemName":  "Bottom Cover - 3601 (184mm)",
        "unit":  "Pcs",
        "opening":  6593,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  4000,
        "prodReceive":  4000,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  14593,
        "consumption":  6000,
        "wipIssue":  4000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  10000,
        "closing":  4593,
        "binClosing":  4593,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  43,
        "origSl":  "366",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100129",
        "code":  "SFG1010132",
        "itemName":  "Bottom Cover - 5607",
        "unit":  "Pcs",
        "opening":  2341,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  800,
        "prodReceive":  0,
        "damageReceive":  281,
        "othersReceive":  0,
        "totalReceive":  3422,
        "consumption":  0,
        "wipIssue":  800,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  281,
        "inTransit":  0,
        "totalIssue":  1081,
        "closing":  2341,
        "binClosing":  2341,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  44,
        "origSl":  "367",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100011",
        "code":  "SFG1010011",
        "itemName":  "Bottom Cover-4801 (220mm)",
        "unit":  "Pcs",
        "opening":  3630,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  7600,
        "prodReceive":  2700,
        "damageReceive":  175,
        "othersReceive":  0,
        "totalReceive":  14105,
        "consumption":  2000,
        "wipIssue":  7600,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  175,
        "inTransit":  0,
        "totalIssue":  9775,
        "closing":  4330,
        "binClosing":  4330,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  45,
        "origSl":  "368",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100012",
        "code":  "SFG1010012",
        "itemName":  "Bottom Cover-5601 (232mm)",
        "unit":  "Pcs",
        "opening":  29894,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  21615,
        "prodReceive":  1500,
        "damageReceive":  641,
        "othersReceive":  0,
        "totalReceive":  53650,
        "consumption":  12980,
        "wipIssue":  21615,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  641,
        "inTransit":  0,
        "totalIssue":  35236,
        "closing":  18414,
        "binClosing":  18414,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  46,
        "origSl":  "369",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100013",
        "code":  "SFG1010013",
        "itemName":  "Bottom Cover-5602 (217mm)",
        "unit":  "Pcs",
        "opening":  96,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  15374,
        "prodReceive":  7800,
        "damageReceive":  247,
        "othersReceive":  0,
        "totalReceive":  23517,
        "consumption":  0,
        "wipIssue":  15374,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  247,
        "inTransit":  0,
        "totalIssue":  15621,
        "closing":  7896,
        "binClosing":  7896,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  47,
        "origSl":  "370",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100086",
        "code":  "SFG1010091",
        "itemName":  "Bottom Cover-5603 (232mm)",
        "unit":  "Pcs",
        "opening":  3551,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  2388,
        "prodReceive":  0,
        "damageReceive":  168,
        "othersReceive":  0,
        "totalReceive":  6107,
        "consumption":  900,
        "wipIssue":  2388,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  168,
        "inTransit":  0,
        "totalIssue":  3456,
        "closing":  2651,
        "binClosing":  2651,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  48,
        "origSl":  "371",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100027",
        "code":  "SFG1010027",
        "itemName":  "Complete Armature 5.5 Circle 16mm",
        "unit":  "Pcs",
        "opening":  60,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1742,
        "prodReceive":  1742,
        "damageReceive":  0,
        "othersReceive":  60,
        "totalReceive":  3604,
        "consumption":  1691,
        "wipIssue":  1802,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  3493,
        "closing":  111,
        "binClosing":  111,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  49,
        "origSl":  "372",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100028",
        "code":  "SFG1010028",
        "itemName":  "Complete Armature 6 Circle 16mm",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1241,
        "prodReceive":  1241,
        "damageReceive":  0,
        "othersReceive":  74,
        "totalReceive":  2556,
        "consumption":  1167,
        "wipIssue":  1315,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2482,
        "closing":  74,
        "binClosing":  74,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  50,
        "origSl":  "373",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100030",
        "code":  "SFG1010030",
        "itemName":  "Complete Armature 7 Circle 15mm",
        "unit":  "Pcs",
        "opening":  6095,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  22914,
        "prodReceive":  16824,
        "damageReceive":  0,
        "othersReceive":  300,
        "totalReceive":  46133,
        "consumption":  22122,
        "wipIssue":  23214,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  45336,
        "closing":  797,
        "binClosing":  797,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  51,
        "origSl":  "374",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100138",
        "code":  "SFG1010141",
        "itemName":  "Complete Armature 7 Circle 16mm -5606",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  60,
        "prodReceive":  60,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  120,
        "consumption":  60,
        "wipIssue":  60,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  120,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  52,
        "origSl":  "375",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100120",
        "code":  "SFG1010123",
        "itemName":  "Complete Armature 7 Circle 16mm -5607",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  336,
        "prodReceive":  336,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  672,
        "consumption":  0,
        "wipIssue":  336,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  336,
        "closing":  336,
        "binClosing":  336,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  53,
        "origSl":  "376",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100070",
        "code":  "SFG1010070",
        "itemName":  "Complete Canopy Big - 4801, 5601, 5603",
        "unit":  "Set",
        "opening":  9105,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  25724,
        "damageReceive":  0,
        "othersReceive":  200,
        "totalReceive":  35029,
        "consumption":  24935,
        "wipIssue":  411,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  25346,
        "closing":  9683,
        "binClosing":  9683,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  54,
        "origSl":  "377",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100105",
        "code":  "SFG1010110",
        "itemName":  "Complete Canopy Big-5601-White",
        "unit":  "Pcs",
        "opening":  600,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  600,
        "consumption":  105,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  105,
        "closing":  495,
        "binClosing":  495,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  55,
        "origSl":  "378",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100069",
        "code":  "SFG1010069",
        "itemName":  "Complete Canopy Small-5602",
        "unit":  "Pcs",
        "opening":  1058,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  322,
        "damageReceive":  0,
        "othersReceive":  74,
        "totalReceive":  1454,
        "consumption":  0,
        "wipIssue":  74,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  74,
        "closing":  1380,
        "binClosing":  1380,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  56,
        "origSl":  "379",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100065",
        "code":  "SFG1010065",
        "itemName":  "Complete Down Pipe 10 Inch -(5602,3601,2401)- Ivory",
        "unit":  "Pcs",
        "opening":  2498,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  5884,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  8382,
        "consumption":  1691,
        "wipIssue":  185,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1876,
        "closing":  6506,
        "binClosing":  6506,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  57,
        "origSl":  "380",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100064",
        "code":  "SFG1010064",
        "itemName":  "Complete Down Pipe 10 Inch- 4801, 5601, 5603 - Ivory",
        "unit":  "Pcs",
        "opening":  14245,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  11253,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  25498,
        "consumption":  23244,
        "wipIssue":  300,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  23544,
        "closing":  1954,
        "binClosing":  1954,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  58,
        "origSl":  "381",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100110",
        "code":  "SFG1010115",
        "itemName":  "Complete Down Pipe 10 Inch- 5601- White",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  335,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  335,
        "consumption":  105,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  105,
        "closing":  230,
        "binClosing":  230,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  59,
        "origSl":  "382",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100039",
        "code":  "SFG1010039",
        "itemName":  "Complete Rotor 5.5 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  208,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  5473,
        "prodReceive":  4680,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  10361,
        "consumption":  1691,
        "wipIssue":  5473,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  7164,
        "closing":  3197,
        "binClosing":  3197,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  60,
        "origSl":  "383",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100040",
        "code":  "SFG1010040",
        "itemName":  "Complete Rotor 6 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  1368,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1342,
        "prodReceive":  100,
        "damageReceive":  0,
        "othersReceive":  74,
        "totalReceive":  2884,
        "consumption":  1167,
        "wipIssue":  1416,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2583,
        "closing":  301,
        "binClosing":  301,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  61,
        "origSl":  "384",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100042",
        "code":  "SFG1010042",
        "itemName":  "Complete Rotor 7 Circle 14.5mm",
        "unit":  "Pcs",
        "opening":  7126,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  23870,
        "prodReceive":  19905,
        "damageReceive":  0,
        "othersReceive":  300,
        "totalReceive":  51201,
        "consumption":  22122,
        "wipIssue":  24170,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  46292,
        "closing":  4909,
        "binClosing":  4909,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  62,
        "origSl":  "385",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100123",
        "code":  "SFG1010126",
        "itemName":  "Complete Rotor 7 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  241,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  351,
        "prodReceive":  351,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  943,
        "consumption":  60,
        "wipIssue":  351,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  411,
        "closing":  532,
        "binClosing":  532,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  63,
        "origSl":  "386",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100082",
        "code":  "SFG1010082",
        "itemName":  "Completed Clamp with Accessories - 4801, 5601, 5603",
        "unit":  "Set",
        "opening":  17830,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  8817,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  26647,
        "consumption":  23349,
        "wipIssue":  300,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  23649,
        "closing":  2998,
        "binClosing":  2998,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  64,
        "origSl":  "387",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100139",
        "code":  "SFG1010142",
        "itemName":  "Completed Clamp with Accessories - 5607",
        "unit":  "Set",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  336,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  336,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  336,
        "binClosing":  336,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  65,
        "origSl":  "388",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100097",
        "code":  "SFG1010102",
        "itemName":  "Down Pipe 1 Inch - Ivory",
        "unit":  "Inch",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  22000,
        "prodReceive":  22000,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  44000,
        "consumption":  22000,
        "wipIssue":  22000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  44000,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  66,
        "origSl":  "389",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100061",
        "code":  "SFG1010061",
        "itemName":  "Down Pipe 10 Inch -(5602,3601,2401)",
        "unit":  "Pcs",
        "opening":  4400,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  50,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  4450,
        "consumption":  4400,
        "wipIssue":  50,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  4450,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  67,
        "origSl":  "390",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100060",
        "code":  "SFG1010060",
        "itemName":  "Down Pipe 10 Inch- 4801, 5601, 5603",
        "unit":  "Pcs",
        "opening":  3755,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  22669,
        "prodReceive":  19957,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  46381,
        "consumption":  19956,
        "wipIssue":  22669,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  42625,
        "closing":  3756,
        "binClosing":  3756,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  68,
        "origSl":  "391",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100066",
        "code":  "SFG1010066",
        "itemName":  "Down Pipe Clamp - 4801, 5601, 5603",
        "unit":  "Set",
        "opening":  28491,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  15000,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  43491,
        "consumption":  9153,
        "wipIssue":  15000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  24153,
        "closing":  19338,
        "binClosing":  19338,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  69,
        "origSl":  "392",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100096",
        "code":  "SFG1010101",
        "itemName":  "FAN Aluminium Bar",
        "unit":  "KG",
        "opening":  114.256,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  29721,
        "damageReceive":  0,
        "othersReceive":  500,
        "totalReceive":  30335.256,
        "consumption":  30334.4,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  30334.4,
        "closing":  0.856,
        "binClosing":  0.856,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  70,
        "origSl":  "393",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100116",
        "code":  "SFG1010119",
        "itemName":  "Fan Promotional Gang Regulator White (P512)",
        "unit":  "Pcs",
        "opening":  627,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  627,
        "consumption":  48,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  48,
        "closing":  579,
        "binClosing":  579,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  71,
        "origSl":  "394",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100081",
        "code":  "SFG1010081",
        "itemName":  "MEP Fan Regulator - 3601, 4801, 5601, 5603",
        "unit":  "Pcs",
        "opening":  11644,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  17457,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  29101,
        "consumption":  23845,
        "wipIssue":  411,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  24256,
        "closing":  4845,
        "binClosing":  4845,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  72,
        "origSl":  "395",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100046",
        "code":  "SFG1010046",
        "itemName":  "MS Blade 2401 (Sheet)",
        "unit":  "Set",
        "opening":  14,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  14,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  14,
        "binClosing":  14,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  73,
        "origSl":  "396",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100047",
        "code":  "SFG1010047",
        "itemName":  "MS Blade 5602 (Sheet)",
        "unit":  "Set",
        "opening":  210,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  210,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  210,
        "binClosing":  210,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  74,
        "origSl":  "397",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100062",
        "code":  "SFG1010062",
        "itemName":  "Painted Down Pipe 10 Inch- 4801, 5601, 5603 - Ivory",
        "unit":  "Pcs",
        "opening":  13075,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  18645,
        "prodReceive":  19621,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  51341,
        "consumption":  11253,
        "wipIssue":  18645,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  29898,
        "closing":  21443,
        "binClosing":  21443,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  75,
        "origSl":  "398",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100109",
        "code":  "SFG1010114",
        "itemName":  "Painted Down Pipe 10 Inch- 4801, 5601, 5603 - White",
        "unit":  "Pcs",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  335,
        "prodReceive":  335,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  670,
        "consumption":  335,
        "wipIssue":  335,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  670,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  76,
        "origSl":  "399",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100063",
        "code":  "SFG1010063",
        "itemName":  "Painted Down Pipe 10 Inch-5602,3601,2401 - Ivory",
        "unit":  "Pcs",
        "opening":  6146,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  7491,
        "prodReceive":  4400,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  18037,
        "consumption":  5884,
        "wipIssue":  7491,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  13375,
        "closing":  4662,
        "binClosing":  4662,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  77,
        "origSl":  "400",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100055",
        "code":  "SFG1010055",
        "itemName":  "Painting Blade 2401-Ivory",
        "unit":  "Set",
        "opening":  5538,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  4223,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  9761,
        "consumption":  3840,
        "wipIssue":  4223,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  8063,
        "closing":  1698,
        "binClosing":  1698,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  78,
        "origSl":  "401",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100056",
        "code":  "SFG1010056",
        "itemName":  "Painting Blade 3601-Ivory",
        "unit":  "Set",
        "opening":  3265,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  2766,
        "prodReceive":  1600,
        "damageReceive":  0,
        "othersReceive":  1,
        "totalReceive":  7632,
        "consumption":  1860,
        "wipIssue":  2767,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  4627,
        "closing":  3005,
        "binClosing":  3005,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  79,
        "origSl":  "402",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100057",
        "code":  "SFG1010057",
        "itemName":  "Painting Blade 4801-Ivory",
        "unit":  "Set",
        "opening":  590,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  255,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  845,
        "consumption":  213,
        "wipIssue":  255,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  468,
        "closing":  377,
        "binClosing":  377,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  80,
        "origSl":  "403",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100058",
        "code":  "SFG1010058",
        "itemName":  "Painting Blade 5601-Ivory",
        "unit":  "Set",
        "opening":  3373,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  29070,
        "prodReceive":  13332,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  45775,
        "consumption":  15749,
        "wipIssue":  29070,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  44819,
        "closing":  956,
        "binClosing":  956,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  81,
        "origSl":  "404",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100102",
        "code":  "SFG1010107",
        "itemName":  "Painting Blade 5601-White",
        "unit":  "Set",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  218,
        "prodReceive":  218,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  436,
        "consumption":  218,
        "wipIssue":  218,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  436,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  82,
        "origSl":  "405",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100059",
        "code":  "SFG1010059",
        "itemName":  "Painting Blade 5602-Ivory",
        "unit":  "Set",
        "opening":  1121,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  300,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1421,
        "consumption":  0,
        "wipIssue":  300,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  300,
        "closing":  1121,
        "binClosing":  1121,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  83,
        "origSl":  "406",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100090",
        "code":  "SFG1010095",
        "itemName":  "Painting Blade 5603-Ivory",
        "unit":  "Set",
        "opening":  419,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  2800,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  3219,
        "consumption":  0,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  0,
        "closing":  3219,
        "binClosing":  3219,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  84,
        "origSl":  "407",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100127",
        "code":  "SFG1010130",
        "itemName":  "Painting Blade 5607 - Ivory",
        "unit":  "Set",
        "opening":  1347,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  694,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  2041,
        "consumption":  263,
        "wipIssue":  694,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  957,
        "closing":  1084,
        "binClosing":  1084,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  85,
        "origSl":  "408",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100131",
        "code":  "SFG1010134",
        "itemName":  "Painting Bottom Cover 5607 - Ivory",
        "unit":  "Pcs",
        "opening":  787,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  412,
        "prodReceive":  0,
        "damageReceive":  63,
        "othersReceive":  0,
        "totalReceive":  1262,
        "consumption":  0,
        "wipIssue":  412,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  63,
        "inTransit":  0,
        "totalIssue":  475,
        "closing":  787,
        "binClosing":  787,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  86,
        "origSl":  "409",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100014",
        "code":  "SFG1010014",
        "itemName":  "Painting Bottom Cover-2401 (184mm) - Ivory",
        "unit":  "Pcs",
        "opening":  924,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1150,
        "prodReceive":  2976,
        "damageReceive":  13,
        "othersReceive":  0,
        "totalReceive":  5063,
        "consumption":  1091,
        "wipIssue":  1150,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  13,
        "inTransit":  0,
        "totalIssue":  2254,
        "closing":  2809,
        "binClosing":  2809,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  87,
        "origSl":  "410",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100015",
        "code":  "SFG1010015",
        "itemName":  "Painting Bottom Cover-3601 (184mm) - Ivory",
        "unit":  "Pcs",
        "opening":  2442,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  3350,
        "prodReceive":  6000,
        "damageReceive":  3,
        "othersReceive":  111,
        "totalReceive":  11906,
        "consumption":  600,
        "wipIssue":  3461,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  3,
        "inTransit":  0,
        "totalIssue":  4064,
        "closing":  7842,
        "binClosing":  7842,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  88,
        "origSl":  "411",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100016",
        "code":  "SFG1010016",
        "itemName":  "Painting Bottom Cover-4801 (220mm) - Ivory",
        "unit":  "Pcs",
        "opening":  1842,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1250,
        "prodReceive":  2000,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  5092,
        "consumption":  1167,
        "wipIssue":  1250,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2417,
        "closing":  2675,
        "binClosing":  2675,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  89,
        "origSl":  "412",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100017",
        "code":  "SFG1010017",
        "itemName":  "Painting Bottom Cover-5601 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  16267,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  21680,
        "prodReceive":  12900,
        "damageReceive":  545,
        "othersReceive":  300,
        "totalReceive":  51692,
        "consumption":  21755,
        "wipIssue":  21980,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  545,
        "inTransit":  0,
        "totalIssue":  44280,
        "closing":  7412,
        "binClosing":  7412,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  90,
        "origSl":  "413",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100101",
        "code":  "SFG1010106",
        "itemName":  "Painting Bottom Cover-5601 (232mm) - White",
        "unit":  "Pcs",
        "opening":  150,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  230,
        "prodReceive":  80,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  460,
        "consumption":  105,
        "wipIssue":  230,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  335,
        "closing":  125,
        "binClosing":  125,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  91,
        "origSl":  "414",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100018",
        "code":  "SFG1010018",
        "itemName":  "Painting Bottom Cover-5602 (217mm) - Ivory",
        "unit":  "Pcs",
        "opening":  4173,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  117,
        "prodReceive":  0,
        "damageReceive":  8,
        "othersReceive":  74,
        "totalReceive":  4372,
        "consumption":  0,
        "wipIssue":  191,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  8,
        "inTransit":  0,
        "totalIssue":  199,
        "closing":  4173,
        "binClosing":  4173,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  92,
        "origSl":  "415",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100087",
        "code":  "SFG1010092",
        "itemName":  "Painting Bottom Cover-5603 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  719,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  900,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1619,
        "consumption":  322,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  322,
        "closing":  1297,
        "binClosing":  1297,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  93,
        "origSl":  "416",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100098",
        "code":  "SFG1010103",
        "itemName":  "Painting Down pipe 1 Inch",
        "unit":  "Inch",
        "opening":  0,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  22000,
        "prodReceive":  22000,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  44000,
        "consumption":  22000,
        "wipIssue":  22000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  44000,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  94,
        "origSl":  "417",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100130",
        "code":  "SFG1010133",
        "itemName":  "Painting Top Cover 5607 - Ivory",
        "unit":  "Pcs",
        "opening":  870,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  410,
        "prodReceive":  0,
        "damageReceive":  31,
        "othersReceive":  0,
        "totalReceive":  1311,
        "consumption":  0,
        "wipIssue":  410,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  31,
        "inTransit":  0,
        "totalIssue":  441,
        "closing":  870,
        "binClosing":  870,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  95,
        "origSl":  "418",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100005",
        "code":  "SFG1010005",
        "itemName":  "Painting Top Cover-2401 (184mm)- Ivory",
        "unit":  "Pcs",
        "opening":  2488,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1150,
        "prodReceive":  950,
        "damageReceive":  24,
        "othersReceive":  0,
        "totalReceive":  4612,
        "consumption":  1091,
        "wipIssue":  1150,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  24,
        "inTransit":  0,
        "totalIssue":  2265,
        "closing":  2347,
        "binClosing":  2347,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  96,
        "origSl":  "419",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100006",
        "code":  "SFG1010006",
        "itemName":  "Painting Top Cover-3601 (184mm) - Ivory",
        "unit":  "Pcs",
        "opening":  761,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  3574,
        "prodReceive":  7000,
        "damageReceive":  29,
        "othersReceive":  111,
        "totalReceive":  11475,
        "consumption":  600,
        "wipIssue":  3685,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  29,
        "inTransit":  0,
        "totalIssue":  4314,
        "closing":  7161,
        "binClosing":  7161,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  97,
        "origSl":  "420",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100007",
        "code":  "SFG1010007",
        "itemName":  "Painting Top Cover-4801 (220mm) - Ivory",
        "unit":  "Pcs",
        "opening":  1398,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  1250,
        "prodReceive":  2500,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  5148,
        "consumption":  1167,
        "wipIssue":  1250,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  2417,
        "closing":  2731,
        "binClosing":  2731,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  98,
        "origSl":  "421",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100008",
        "code":  "SFG1010008",
        "itemName":  "Painting Top Cover-5601 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  16897,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  22868,
        "prodReceive":  7700,
        "damageReceive":  94,
        "othersReceive":  300,
        "totalReceive":  47859,
        "consumption":  21755,
        "wipIssue":  23168,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  94,
        "inTransit":  0,
        "totalIssue":  45017,
        "closing":  2842,
        "binClosing":  2842,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  99,
        "origSl":  "422",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100100",
        "code":  "SFG1010105",
        "itemName":  "Painting Top Cover-5601 (232mm) - White",
        "unit":  "Pcs",
        "opening":  15,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  230,
        "prodReceive":  215,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  460,
        "consumption":  105,
        "wipIssue":  230,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  335,
        "closing":  125,
        "binClosing":  125,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  100,
        "origSl":  "423",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100009",
        "code":  "SFG1010009",
        "itemName":  "Painting Top Cover-5602 (217mm) - Ivory",
        "unit":  "Pcs",
        "opening":  4005,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  121,
        "prodReceive":  0,
        "damageReceive":  11,
        "othersReceive":  74,
        "totalReceive":  4211,
        "consumption":  0,
        "wipIssue":  195,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  11,
        "inTransit":  0,
        "totalIssue":  206,
        "closing":  4005,
        "binClosing":  4005,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  101,
        "origSl":  "424",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100085",
        "code":  "SFG1010090",
        "itemName":  "Painting Top Cover-5603 (232mm) - Ivory",
        "unit":  "Pcs",
        "opening":  1205,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  3000,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  4205,
        "consumption":  322,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  322,
        "closing":  3883,
        "binClosing":  3883,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  102,
        "origSl":  "425",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100034",
        "code":  "SFG1010034",
        "itemName":  "Rotor 7 Circle 14.5mm",
        "unit":  "Pcs",
        "opening":  24140,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  21886,
        "prodReceive":  23595,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  69621,
        "consumption":  34505,
        "wipIssue":  21886,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  56391,
        "closing":  13230,
        "binClosing":  13230,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  103,
        "origSl":  "426",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100035",
        "code":  "SFG1010035",
        "itemName":  "Rotor with Ingot 5.5 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  16896,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  68,
        "othersReceive":  0,
        "totalReceive":  16964,
        "consumption":  4680,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  68,
        "inTransit":  0,
        "totalIssue":  4748,
        "closing":  12216,
        "binClosing":  12216,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  104,
        "origSl":  "427",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100036",
        "code":  "SFG1010036",
        "itemName":  "Rotor with Ingot 6 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  12077,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  78,
        "othersReceive":  0,
        "totalReceive":  12155,
        "consumption":  100,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  78,
        "inTransit":  0,
        "totalIssue":  178,
        "closing":  11977,
        "binClosing":  11977,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  105,
        "origSl":  "428",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100038",
        "code":  "SFG1010038",
        "itemName":  "Rotor with Ingot 7 Circle 14.5mm",
        "unit":  "Pcs",
        "opening":  20586,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  34505,
        "prodReceive":  34505,
        "damageReceive":  168,
        "othersReceive":  0,
        "totalReceive":  89764,
        "consumption":  19905,
        "wipIssue":  34505,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  168,
        "inTransit":  0,
        "totalIssue":  54578,
        "closing":  35186,
        "binClosing":  35186,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  106,
        "origSl":  "429",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100122",
        "code":  "SFG1010125",
        "itemName":  "Rotor with Ingot 7 Circle 15.5mm",
        "unit":  "Pcs",
        "opening":  1909,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  1909,
        "consumption":  351,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  351,
        "closing":  1558,
        "binClosing":  1558,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  107,
        "origSl":  "430",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100083",
        "code":  "SFG1010083",
        "itemName":  "Top Cover - 3601 (184mm)",
        "unit":  "Pcs",
        "opening":  8848,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  8000,
        "prodReceive":  4000,
        "damageReceive":  3,
        "othersReceive":  0,
        "totalReceive":  20851,
        "consumption":  7000,
        "wipIssue":  8000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  3,
        "inTransit":  0,
        "totalIssue":  15003,
        "closing":  5848,
        "binClosing":  5848,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  108,
        "origSl":  "431",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100001",
        "code":  "SFG1010001",
        "itemName":  "Top Cover - 2401 (184mm)",
        "unit":  "Pcs",
        "opening":  2462,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  2462,
        "consumption":  950,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  950,
        "closing":  1512,
        "binClosing":  1512,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  109,
        "origSl":  "432",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100128",
        "code":  "SFG1010131",
        "itemName":  "Top Cover - 5607",
        "unit":  "Pcs",
        "opening":  992,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  200,
        "prodReceive":  0,
        "damageReceive":  42,
        "othersReceive":  0,
        "totalReceive":  1234,
        "consumption":  0,
        "wipIssue":  200,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  42,
        "inTransit":  0,
        "totalIssue":  242,
        "closing":  992,
        "binClosing":  992,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  110,
        "origSl":  "433",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100002",
        "code":  "SFG1010002",
        "itemName":  "Top Cover-4801 (220mm)",
        "unit":  "Pcs",
        "opening":  2697,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  7100,
        "prodReceive":  3200,
        "damageReceive":  231,
        "othersReceive":  0,
        "totalReceive":  13228,
        "consumption":  2500,
        "wipIssue":  7100,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  231,
        "inTransit":  0,
        "totalIssue":  9831,
        "closing":  3397,
        "binClosing":  3397,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  111,
        "origSl":  "434",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100003",
        "code":  "SFG1010003",
        "itemName":  "Top Cover-5601 (232mm)",
        "unit":  "Pcs",
        "opening":  30053,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  12452,
        "prodReceive":  1000,
        "damageReceive":  218,
        "othersReceive":  0,
        "totalReceive":  43723,
        "consumption":  7915,
        "wipIssue":  12452,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  218,
        "inTransit":  0,
        "totalIssue":  20585,
        "closing":  23138,
        "binClosing":  23138,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  112,
        "origSl":  "435",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100004",
        "code":  "SFG1010004",
        "itemName":  "Top Cover-5602 (217mm)",
        "unit":  "Pcs",
        "opening":  1106,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  12300,
        "prodReceive":  7800,
        "damageReceive":  175,
        "othersReceive":  0,
        "totalReceive":  21381,
        "consumption":  0,
        "wipIssue":  12300,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  175,
        "inTransit":  0,
        "totalIssue":  12475,
        "closing":  8906,
        "binClosing":  8906,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  113,
        "origSl":  "436",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100084",
        "code":  "SFG1010084",
        "itemName":  "Top Cover-5603 (232mm)",
        "unit":  "Pcs",
        "opening":  3000,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  3000,
        "prodReceive":  0,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  6000,
        "consumption":  3000,
        "wipIssue":  3000,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  6000,
        "closing":  0,
        "binClosing":  0,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  114,
        "origSl":  "437",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100023",
        "code":  "SFG1010023",
        "itemName":  "Winding Armature 5.5 Circle 16mm",
        "unit":  "Pcs",
        "opening":  3174,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  1850,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  5024,
        "consumption":  1742,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1742,
        "closing":  3282,
        "binClosing":  3282,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  115,
        "origSl":  "438",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100024",
        "code":  "SFG1010024",
        "itemName":  "Winding Armature 6 Circle 16mm",
        "unit":  "Pcs",
        "opening":  2123,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  178,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  2301,
        "consumption":  1241,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  1241,
        "closing":  1060,
        "binClosing":  1060,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  116,
        "origSl":  "439",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100026",
        "code":  "SFG1010026",
        "itemName":  "Winding Armature 7 Circle 15mm",
        "unit":  "Pcs",
        "opening":  11331,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  11500,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  22831,
        "consumption":  16824,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  16824,
        "closing":  6007,
        "binClosing":  6007,
        "diff":  0,
        "remarks":  ""
    },
    {
        "sl":  117,
        "origSl":  "440",
        "company":  "FAN",
        "category":  "FAN SFG",
        "erpCode":  "1300100119",
        "code":  "SFG1010122",
        "itemName":  "Winding Armature 7 Circle 16mm",
        "unit":  "Pcs",
        "opening":  788,
        "openingAdjust":  0,
        "storeReceive":  0,
        "sectionReceive":  0,
        "prodReceive":  160,
        "damageReceive":  0,
        "othersReceive":  0,
        "totalReceive":  948,
        "consumption":  396,
        "wipIssue":  0,
        "openingAdjustIssue":  0,
        "issueToRepair":  0,
        "issueToDamage":  0,
        "inTransit":  0,
        "totalIssue":  396,
        "closing":  552,
        "binClosing":  552,
        "diff":  0,
        "remarks":  ""
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { RAW_CLOSING_ALL_SFG_DATA };
}
